<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-BG83L86" failures="1" tests="5" name="com.bank.api.tests.UserProfileManagementTests" time="3.325" errors="0" timestamp="2024-12-29T15:48:32 IST" skipped="0">
  <testcase classname="com.bank.api.tests.UserProfileManagementTests" name="verifyGetUserProfile" time="0.428"/>
  <testcase classname="com.bank.api.tests.UserProfileManagementTests" name="verifyUpdateUserProfileWithPutRequest" time="0.204"/>
  <testcase classname="com.bank.api.tests.UserProfileManagementTests" name="verifyUpdateUserProfileWithPatchRequest" time="0.159"/>
  <testcase classname="com.bank.api.tests.UserProfileManagementTests" name="verifyChangePassword" time="0.353"/>
  <testcase classname="com.bank.api.tests.UserProfileManagementTests" name="verifyDeleteUserProfile" time="2.181">
    <failure message="expected [User profile deleted successfully] but found [{
    &quot;timestamp&quot;: &quot;Sun Dec 29 10:18:30 UTC 2024&quot;,
    &quot;status&quot;: 401,
    &quot;error&quot;: &quot;Unauthorized&quot;,
    &quot;message&quot;: &quot;Full authentication is required to access this resource&quot;,
    &quot;path&quot;: &quot;/error&quot;
}]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [User profile deleted successfully] but found [{
    "timestamp": "Sun Dec 29 10:18:30 UTC 2024",
    "status": 401,
    "error": "Unauthorized",
    "message": "Full authentication is required to access this resource",
    "path": "/error"
}]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at com.bank.api.tests.UserProfileManagementTests.verifyDeleteUserProfile(UserProfileManagementTests.java:111)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- verifyDeleteUserProfile -->
</testsuite> <!-- com.bank.api.tests.UserProfileManagementTests -->
